### ISSUE TITLE
查找英语单词那个可以修改吗？

### ISSUE THREAD

**Issue by xp12047** [pnlpal/dictionariez#105]
![image](https://user-images.githubusercontent.com/56335408/212464617-0a1679a1-9639-43a2-b986-52508a588410.png)
这三个我都不太想用。我可以修改别的为默认吗？例如deepl      
如果可以修改方便给个例子吗？  谢谢。   
增加词典我倒是勉强会操作了。   
这个工具真的很棒。感谢你开发了这么好用的工具。

**Comment by revir** [comment]
这个查词的来源比较麻烦，目前我恐怕不准备添加别的来源了。 如果你想自己添加，可以考虑 pull request， 谢谢。

**Comment by xp12047** [comment]
> 

哦，谢谢
