### ISSUE TITLE
Adding dicts error: Content Security Policy of your site blocks the use of 'eval' in JavaScript`

### ISSUE THREAD

**Issue by Ultrafeel** [pnlpal/dictionariez#114]
Here is in console:
> Content Security Policy of your site blocks the use of 'eval' in JavaScript`
> The Content Security Policy (CSP) prevents the evaluation of arbitrary strings as JavaScript to make it more difficult for an attacker to inject unathorized code on your site.
> To solve this issue, avoid using eval(), new Function(), setTimeout([string], ...) and setInterval([string], ...) for evaluating strings.
> If you absolutely must: you can enable string evaluation by adding unsafe-eval as an allowed source in a script-src directive.
> ⚠️ Allowing string evaluation comes at the risk of inline script injection.
> 1 directive
> Source Location	Directive	Status
> angular.js:1292	script-src	blocked
> Learn more: Content Security Policy - Eval

I know I can put a command to add a dict. But could you somehow add option to get dump of added dicts as a json to add them as a batch with JS command.

**Comment by revir** [comment]
Not sure about how to reproduce it. Would you just want to have the functionality of batch importing dicts?
