### ISSUE TITLE
Floating definition while using VPN not working

### ISSUE THREAD

**Issue by KorvinSilver** [pnlpal/dictionariez#122]
The floating definition doesn't work if I'm connected to a VPN, it shows it loading for a moment then disappears. Maybe it times out.

**Comment by revir** [comment]
It's a network issue on your side, by default this dict will use Google as the source,  you can change it to wiktionary or Bing instead. 
![image](https://github.com/pnlpal/dictionariez/assets/3252034/d51f0783-13ee-42f0-ab82-c286a47e4ad9)
