### ISSUE TITLE
How to edit entry and add wordreference bilingual dictionary?

### ISSUE THREAD

**Issue by omega3** [pnlpal/dictionariez#124]
How can I add to dictionaries bilingual dictionary?
https://www.wordreference.com/enpl/

How to edit addExtraDict entry?
You say [here](https://pnlpal.dev/topic/52/help-more-dictionaries-needed) By code: At the settings page, open chrome's devtool, use function like this:

But how to do it on Firefox? Where is the config file?

**Comment by Mapik0** [comment]
It's the same as in Chrome.
1. Go to Dictionariez settings. You can do it by opening the Dictionariez extension page and press the **Go to the settings**.

![image](https://github.com/pnlpal/dictionariez/assets/163001685/43115804-2761-4701-b1ad-813282b16f7f)

2. Now press F12 to open Mozila devtools. You'll see the console (if not chose the "console" tab), and the welcoming massage of Dictionariez will appear.

![image](https://github.com/pnlpal/dictionariez/assets/163001685/e65a5089-bf17-4aba-a65f-4f3413ee6449)

3. Now just follow the instructions that are written on the welcome message.
Pay attention! If it's the first time you work with the console, it will not let you insert your code easily, carefully read the massage that the console will tell you when you try to insert the code in the console.

![image](https://github.com/pnlpal/dictionariez/assets/163001685/01f38f72-1945-4f51-9e7f-3d7aacc5a088)
