### ISSUE TITLE
captions box keeps scrolling over current text

### ISSUE THREAD

**Issue by AlexDeFoc** [pnlpal/dictionariez#125]
Idk why but any kind of caption or single or multicaptions, when you are at a current time, and the text scrolls it scrolls right over the current text. Why on A54 mobile

**Comment by revir** [comment]
This issue I believe has been solved finally. Sorry I didn't fix it sooner. It has been a while since I began to have time to work on Captionz again. 


![image](https://github.com/user-attachments/assets/31f5a763-8c22-47de-855b-3026e298a232)
