### ISSUE TITLE
[Suggestion] Change dictionaries' drop-down to a list in sidebar

### ISSUE THREAD

**Issue by iriman** [pnlpal/dictionariez#134]
This way we can reach different dictionaries in a click.

Now we do two clicks, one for opening drop-down and one for the choice.

![image](https://github.com/user-attachments/assets/69b06ca7-5183-47c2-a781-c4aed0394f1a)

**Comment by revir** [comment]
Good idea. I updated in v5.1.4 so that when the mouse moves over the dropdown button the list will be automatically expanded. 
See if it helps. 
The new version is already on Firefox and will be available on Chrome and Edge soon.

**Comment by iriman** [comment]
it's somehow better. thank you!
