### ISSUE TITLE
[idea] Auto fill word for websites not accepting word query in their url

### ISSUE THREAD

**Issue by iriman** [pnlpal/dictionariez#135]
For some websites we must first open the search page, then fill the search form and hit the search button. A boring work when we need to frequently refer to such websites.

Example website: https://aryanpour.com/English-to-Persian.php

This is a great feature if possible, like some extensions that auto fill credential info.

Then we can add some info in json code about appropriate field that should be filled and the search button.

**Comment by revir** [comment]
Good idea, thanks. Fixed in v5.1.4 and SidePal v1.0.1
