### ISSUE TITLE
pdf 

### ISSUE THREAD

**Issue by kamyar92ZZA** [pnlpal/dictionariez#136]
hello 
your extension was working on a PDF opened on Edge or Chrome.
unfortunately, it does not work now when I select a word and then right-click on it and select your extension it does not work, nothing happens.
it is working on Firefox as I check.
Can you help me find out how I can make it work again?
[UserManual.pdf](https://github.com/user-attachments/files/16523147/UserManual.pdf)

**Comment by revir** [comment]
Fixed in v5.1.3, soon will be on Chrome webstore. 
You are right there is a bug when look up words from the context menu in a PDF.

**Comment by kamyar92ZZA** [comment]
thank you
