### ISSUE TITLE
Disable new tab opening on the extension update.

### ISSUE THREAD

**Issue by lifestreamy** [pnlpal/dictionariez#144]
Whenever the extension updates, on my browser's launch or even during regular usage, I get a new intrusive tab opened, sometimes more than once a day, interfering with my workflow. 

It would be helpful to at least allow users to alter this behavior in the extension's settings or plainly to disable it by default.

Sadly, while it proved to be very helpful, I am lately considering removing the extension due to this annoyance. It sometimes opens during important actions. 
![image](https://github.com/user-attachments/assets/20435fb0-b7fa-4dac-a0c6-12a5286b73d3)

**Comment by revir** [comment]
> Whenever the extension updates, on my browser's launch or even during regular usage, I get a new intrusive tab opened, sometimes more than once a day, interfering with my workflow.

I'm really sorry to hear about this issue. The window is only meant to open once after an update to a new version, so it seems there might be a problem with Chrome’s update mechanism. I’ll be disabling this behavior in an upcoming update shortly.

**Comment by revir** [comment]
Now just waiting for Google's review before it's published.

**Comment by lifestreamy** [comment]
Thank you!
