### ISSUE TITLE
[Chrome/Brave] "Disable the lookup item in context menu. (Restart the extension to take effect.)" does nothing 

### ISSUE THREAD

**Issue by Demaar** [pnlpal/dictionariez#145]
I both manually disabled/enabled the Extension and restarted the browser.
I am using the Brave browser but I also tested it on Iron. The option does not work for either of them. Both use the Chrome extension.
On Firefox the Option works fine.

**Comment by revir** [comment]
Thanks for the feedback. Yeah, I found it's different on Brave. Seems Brave never really restart the extension. Its state is persisted and couldn't be changed again by restarting.  I solved it by using api to remove the menu item programmatically in v5.3.0.

V5.3.0 is under review on Chrome and Edge, please stay tuned.
