### ISSUE TITLE
This extension doesn't work on kiwi browser for mobile

### ISSUE THREAD

**Issue by funnybones2015** [pnlpal/dictionariez#68]
As you know, Kiwi browser supports chrome extensions, but this extension doesn't work perfectly on it. when you look up a word, the preset dictionaries couldn't be selected, so it doesn't show any dictionary result.

Hope it be compatible with kiwi as well, so it could be very useful for mobile.

**Comment by revir** [comment]
Now v3.0.0 can run on mobile browsers like Kiwi & Flow. It's on the way...

**Comment by funnybones2015** [comment]
Thank you for updating. Exciting news~~~
