### ISSUE TITLE
双击单词未出现黑框词典 （需要帮助）

### ISSUE THREAD

**Issue by lukiashaw** [pnlpal/dictionariez#78]
其他都是正常的，只是双击后，黑框内未出现词典，只有三点缓冲。如下图：
<img width="221" alt="截屏2022-03-28 21 16 41" src="https://user-images.githubusercontent.com/95762829/160406428-302854f6-5a3c-4f77-9889-bf6a418de9ff.png">

（我非常笨，实在不知道哪里出了问题，希望可以帮帮我，非常感谢！😭
Chrome版本：99.0.4844.51（正式版本）(arm64)
电脑版本：mbp m1芯片 12.2.1

**Comment by revir** [comment]
刷新页面后可以吗？ 另外因为辞典数据来源于google，需要翻墙才能用。如果无法翻墙，试试在设置里将辞典来源改为 Bing.
改了设置后，记得刷新一下文章页面再试。

<img width="920" alt="image" src="https://user-images.githubusercontent.com/3252034/160424022-398a1a78-2aa8-43b1-b86d-7ade760e169e.png">

**Comment by lukiashaw** [comment]
可以了！之前可能是网络的因素，开了全局可以用了。
非常感谢！
