### ISSUE TITLE
When looking up a word in the thefreedictionary.com, its tabs on top are partially blocked by the input box

### ISSUE THREAD

**Issue by funnybones2015** [pnlpal/dictionariez#82]
Pls see the screenshot below:

![image](https://user-images.githubusercontent.com/15063728/166672292-1a9474bb-22a1-4b08-9488-ecc3b66101ce.png)

**Comment by revir** [comment]
Fixed on the next version.

**Comment by funnybones2015** [comment]
> Fixed on the next version.

Thx a lot~~
