### ISSUE TITLE
Is it feasible to provide customizable options of any reference website URL?

### ISSUE THREAD

**Issue by funnybones2015** [pnlpal/dictionariez#83]
Is it feasible to provide costomizable options of any reference website URL? Even though there are a lot of amazing reference websites preconfiged, but there are still some other reference websites that needs to be used.

**Comment by revir** [comment]
Do you mean here? https://pnlpal.dev/category/4/dictionariez-trove

**Comment by funnybones2015** [comment]
> Do you mean here? https://pnlpal.dev/category/4/dictionariez-trove

I know this webpage contains many reference website URLs, but they are ready-made ones. How to customize any other reference websites?
