### ISSUE TITLE
[Bug] Automatic Anki export fails to create cards.

### ISSUE THREAD

**Issue by chrisrhughes** [pnlpal/dictionariez#90]
**Problem:** 
Under word history, selecting an uncommon word for Anki export (e.g. "pleiotropy") fails to create a new card with an appropriate definition. 

A blank card is created and it contains no information. The word's definition is correctly displayed when using the extension within the browser. This occurs with any uncommon words. 

**Expectation:** 
Anki export creates a flash card with the appropriate word and definition using the same definition presented by the extension.

**Comment by revir** [comment]
Added a `skip` button on the next version. 
Feel free to reopen it if it's still not helpful.
