### ISSUE TITLE
Linux Ubuntu 18.04 两个显示器有错误出现.

### ISSUE THREAD

**Issue by sanruby77** [pnlpal/dictionariez#94]
background.html:1 Unchecked runtime.lastError: Cannot access a chrome:// URL
background.html:1 Error handling response: TypeError: Cannot read properties of undefined (reading 'tabs')
    at chrome-extension://diojcfpekhhnndfmggknljpnfpcccbhc/dictwindow.bundle.js:177:31
background.html:1 Unchecked runtime.lastError: Invalid value for bounds. Bounds must be at least 50% within visible screen space.

**Comment by revir** [comment]
should be fixed on the next version. 
feel free to reopen it if not.

**Comment by sanruby77** [comment]
thank your awesome work!
