### ISSUE TITLE
change highlight color

### ISSUE THREAD

**Issue by howarddo2208** [pnlpal/dictionariez#97]
Hi, I normally use the Dark reader extension to make websites easier to read. The problem is when I use the option highlight in yellow after looking up from your extension, the highlight doesn't look good with the dark mode.
![image](https://user-images.githubusercontent.com/62332195/203752188-92d0f27b-09c4-49fb-8b7f-14d1889c2602.png)

I hope that you can implement a way to change the highlight color or somehow recognize the color theme at the moment to change the highlight accordingly, that would be nicer.

**Comment by revir** [comment]
Now with v3.1.0, you could customise the highlight color 👯 
<img width="568" alt="image" src="https://user-images.githubusercontent.com/3252034/207226529-09b944a6-5a0b-40b4-b950-286ca4767b84.png">
