### ISSUE TITLE
Pop-up dictionary not working in Firefox 107.0 (x64) on Win10 Pro 21H2

### ISSUE THREAD

**Issue by fourteen-1** [pnlpal/dictionariez#98]
![firefox_K9XbBU9kgm](https://user-images.githubusercontent.com/73333396/203782355-878a9d24-6711-4a77-bd61-d8f332c96102.gif)

I have (alt) set as my hotkey for pop up dictionary. When I select a word while pressing the alt key, the a pop-up loading window shows up (as shown in gif) but vanishes very quickly.

Please fix this issue, dev. Thank you.

**Comment by revir** [comment]
It couldn't find the definition of the word, did you change the English source or disabled English? 
<img width="346" alt="image" src="https://user-images.githubusercontent.com/3252034/207226364-00a1c81e-2f05-449b-aaac-f5e40311a6dc.png">

**Comment by revir** [comment]
With v3.1.0 it still exists?
